### ISSUE TITLE
Integration with ADF Portal application. Jdev 11g.

### ISSUE THREAD

**Issue by manojcute009** [bdotzour/visualCaptcha-java#1]
Hi All,

I want to integrate this captcha with my adf application. Please help me in this. If possible provide me a jar file. So that this can be added to application and can be used. Please mail me solution at manojcute009@gmail.com

**Comment by bdotzour** [comment]
Hi there -

I've updated the 1.0.0 release to include a pre-built JAR file.  Let me know how it goes as you try to use the library, I'll be interested in your experience and any feedback.

Here's a link to the JAR:  https://github.com/bdotzour/visualCaptcha-java/releases/download/1.0.0/visualCaptcha-java-1.0.0.jar

Cheers!!

**Comment by manojcute009** [comment]
Hi,
Thanks for quick reply,

After adding above jar. it gives me below error:

<10 Feb, 2015 11:27:21 AM IST> <Warning> <Deployer> <BEA-149004> <Failures were detected while initiating deploy task for application 'VisualCaptcha'.> 
<10 Feb, 2015 11:27:21 AM IST> <Warning> <Deployer> <BEA-149078> <Stack trace for message 149004
weblogic.application.ModuleException: Failed to load webapp: 'VisualCaptcha-ViewController-context-root'
    at weblogic.servlet.internal.WebAppModule.prepare(WebAppModule.java:393)
    at weblogic.application.internal.flow.ScopedModuleDriver.prepare(ScopedModuleDriver.java:176)
    at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:199)
    at weblogic.application.internal.flow.DeploymentCallbackFlow$1.next(DeploymentCallbackFlow.java:517)
    at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52)
    Truncated. see log file for complete stacktrace
Caused By: java.lang.UnsupportedClassVersionError: net/dotzour/visualCaptcha/CaptchaServlet : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:630)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:614)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:343)
    Truncated. see log file for complete stacktrace

> [11:27:21 AM] ####  Deployment incomplete.  ####
> [11:27:21 AM] Remote deployment failed (oracle.jdevimpl.deploy.common.Jsr88RemoteDeployer)

Please guide me further

**Comment by bdotzour-widen** [comment]
The issue looks to be a class file version incompatibility.  The library is compiled to target Java 1.7 and you must be using it in a project that is compiling to a an older version.  Which JDK version are you using?
